Support fallbacks configuration with wildcards, e.g. 'fr-*': 'fr'
linagora/i18n-node pull request #6
Opened 2017-06-26 07:44 UTC by kclang

2017-06-26 08:23 UTC, tuanlc approved these changes

2017-06-28 03:26 UTC, sngo25 requested changes

2017-06-28 03:26 UTC, heroandtn3 commented on i18n.js
> +    wildCardChecked) {
bad indent

2017-06-28 03:26 UTC, heroandtn3 commented on i18n.js
> +   * @param {JSON} fallbacks           fallbacks option
should be Object instead of JSON

2017-06-28 03:26 UTC, heroandtn3 commented on i18n.js
> +        var wildCardChecked = {};
what do you use this var for? It seems to be useless

2017-06-28 03:26 UTC, heroandtn3 commented on i18n.js
> +          acceptedLanguages.push(fallback);
this function should not modify the parameters (AKA making side effect), it should return something

2017-06-28 03:26 UTC, heroandtn3 commented on i18n.js
> +   * Setup fallbacks for a given language.
this description is not useful enough

2017-06-28 10:07 UTC, kclang commented on i18n.js
> +        var wildCardChecked = {};
It's used in setupLanguageFallbacks function

2017-06-28 10:08 UTC, kclang commented on i18n.js
> +    wildCardChecked) {
it's good as usual

2017-06-28 10:15 UTC, kclang commented on i18n.js
> +          acceptedLanguages.push(fallback);
re-structured code, please re-check

2017-06-28 10:15 UTC, kclang commented on i18n.js
> +   * @param {JSON} fallbacks           fallbacks option
done

2017-07-04 07:21 UTC, sngo25 requested changes

2017-07-04 07:21 UTC, heroandtn3 commented on i18n.js
> +        var bestMatch = getBestMatchLanguage(acceptedLanguages);
bestMatchLanguage

2017-07-04 07:32 UTC, kclang commented on i18n.js
> +        var bestMatch = getBestMatchLanguage(acceptedLanguages);
changed

2017-07-04 07:39 UTC, sngo25 approved these changes

2017-07-10 05:09 UTC, merged